#spring.main.web-application-type=none
spring.application.ui.title=SciPower
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
server.max-http-request-header-size=20000